# Generated by Django 5.2.6 on 2025-10-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0004_rename_id_track_id_rename_name_track_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(null=True, upload_to='instructor/images')),
                ('status', models.BooleanField(default=True)),
                ('trackid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='track.track')),
            ],
        ),
    ]
