# Generated by Django 5.2.6 on 2025-09-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
