# Generated by Django 5.2.6 on 2025-09-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='status',
            new_name='Status',
        ),
    ]
