# Generated by Django 5.2.6 on 2025-09-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_rename_id_track_id_rename_name_track_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='Status',
            new_name='status',
        ),
    ]
